# Generated by Django 4.2.3 on 2023-08-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_deptdb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctordb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('Experience', models.CharField(blank=True, max_length=50, null=True)),
                ('Education', models.CharField(blank=True, max_length=200, null=True)),
                ('Registrations', models.ImageField(blank=True, null=True, upload_to='')),
                ('Language', models.CharField(blank=True, max_length=100, null=True)),
                ('About', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, max_length=40, null=True)),
                ('Fee', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='dr-img')),
            ],
        ),
    ]
