# Generated by Django 4.2.3 on 2023-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_doctordb'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='Timing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
