# Generated by Django 4.2.3 on 2023-08-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_doctordb_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='Date',
            field=models.DateField(blank=True, max_length=40, null=True),
        ),
    ]
