# Generated by Django 4.2.3 on 2023-08-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_doctordb_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordb',
            name='Date',
        ),
    ]
