# Generated by Django 4.2.3 on 2023-08-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_remove_doctordb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordb',
            name='Registrations',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
