# Generated by Django 4.2.3 on 2023-09-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_doctordb_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordb',
            name='Fee',
        ),
    ]
