# Generated by Django 4.2.3 on 2023-09-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmentdb',
            name='Date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appoinmentdb',
            name='Time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
