# Generated by Django 4.2.3 on 2023-09-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=60, null=True)),
                ('Subject', models.CharField(blank=True, max_length=500, null=True)),
                ('Message', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
