# Generated by Django 4.2.3 on 2023-09-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_blogdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiledb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('Birthday', models.CharField(blank=True, max_length=50, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Image', models.ImageField(unique='ProfileImage', upload_to='')),
            ],
        ),
    ]
