# Generated by Django 4.2.3 on 2023-09-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_profiledb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledb',
            name='Image',
            field=models.ImageField(upload_to='ProfileImage'),
        ),
    ]
