# Generated by Django 4.2.3 on 2023-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_alter_profiledb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrName', models.CharField(blank=True, max_length=50, null=True)),
                ('Registrations', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('Time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
