# Generated by Django 4.2.3 on 2023-09-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_appointmentdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
