# Generated by Django 4.2.3 on 2023-09-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
