# Generated by Django 4.2.3 on 2023-09-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_alter_appointment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
