# Generated by Django 4.2.3 on 2023-09-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
